"""empty message

Revision ID: cf7bdbbc0bcd
Revises: 6dbac50c92f6
Create Date: 2022-07-22 21:59:05.755522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7bdbbc0bcd'
down_revision = '6dbac50c92f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense__entry',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('remark', sa.String(length=100), nullable=False),
    sa.Column('ipaddress', sa.String(length=30), nullable=False),
    sa.Column('createdby', sa.Integer(), nullable=False),
    sa.Column('createdate', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('createtime', sa.Time(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastupdated', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatetime', sa.Time(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_table('expense_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('ipaddress', sa.String(length=30), nullable=False),
    sa.Column('createdby', sa.Integer(), nullable=False),
    sa.Column('createdate', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('createtime', sa.Time(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastupdated', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatetime', sa.Time(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('income__entry',
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('income_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('remark', sa.String(length=100), nullable=False),
    sa.Column('ipaddress', sa.String(length=30), nullable=False),
    sa.Column('createdby', sa.Integer(), nullable=False),
    sa.Column('createdate', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('createtime', sa.Time(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastupdated', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatetime', sa.Time(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('income_id')
    )
    op.create_table('income_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('ipaddress', sa.String(length=30), nullable=False),
    sa.Column('createdby', sa.Integer(), nullable=False),
    sa.Column('createdate', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('createtime', sa.Time(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastupdated', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatetime', sa.Time(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_group')
    op.drop_table('income__entry')
    op.drop_table('expense_group')
    op.drop_table('expense__entry')
    # ### end Alembic commands ###
