"""empty message

Revision ID: ed214f795f8a
Revises: cf7bdbbc0bcd
Create Date: 2022-08-03 23:04:41.658399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed214f795f8a'
down_revision = 'cf7bdbbc0bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createtime', sa.Time(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updatetime', sa.Time(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updatetime')
    op.drop_column('users', 'createtime')
    # ### end Alembic commands ###
